TCAD_GRD_FILE: /home/abhisheks/vg_b4/STARRC/inputs/saed32nm_1p9m_Cmax.nxtgrd
MAPPING_FILE:  /home/abhisheks/vg_b4/STARRC/inputs/saed32nm_tf_itf_tluplus.map
NETLIST_FORMAT: SPEF
BLOCK: route_opt_drc_fixed
NDM_DATABASE: /home/abhisheks/vg_b4/pd/outputs/works/my_ORCA_TOP.nlib
OPERATING_TEMPERATURE: -40
SELECTED_CORNERS: Cmax
NETLIST_FILE: /home/abhisheks/vg_b4/STARRC/outputs/spef/ORCA_TOP.cworst.spef
COUPLE_TO_GROUND: NO
